DROP DATABASE IF EXISTS DB_LISTA;
CREATE DATABASE DB_LISTA;
USE DB_LISTA;

CREATE TABLE PERMISSAO (
	ID_PERMISSAO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(155) NOT NULL,
    INDEX (ID_PERMISSAO)
);

CREATE TABLE USUARIO_CLIENTE (
	ID_USUARIO INTEGER NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    ID_PERMISSAO INTEGER NOT NULL,
    NOME_USUARIO VARCHAR(30) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    NOME_CLIENTE VARCHAR(55) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL,
    PRIMARY KEY(ID_USUARIO, ID_CLIENTE),
    CONSTRAINT FK_ID_PERMISSAO FOREIGN KEY (ID_PERMISSAO) REFERENCES PERMISSAO(ID_PERMISSAO),
    INDEX (ID_USUARIO),
    INDEX (ID_CLIENTE),
    INDEX (ID_PERMISSAO)
);

CREATE TABLE LISTA (
	ID_LISTA INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL,
    ID_CLIENTE INT NOT NULL,
    NOME VARCHAR(55) NOT NULL,
    DATA_LISTA DATE NOT NULL,
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO_CLIENTE(ID_USUARIO),
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO_CLIENTE(ID_CLIENTE),
    INDEX (ID_LISTA),
    INDEX (ID_USUARIO),
    INDEX (ID_CLIENTE)
);

CREATE TABLE SETOR (
	ID_SETOR INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_CADASTRO DATE NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    INDEX (ID_SETOR)
);

CREATE TABLE TIPO_PRODUTO (
	ID_TIPO_PRODUTO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_SETOR INTEGER NOT NULL,
    NOME VARCHAR(55) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    CONSTRAINT FK_ID_SETOR FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR),
    INDEX(ID_TIPO_PRODUTO),
    INDEX(ID_SETOR)
);

CREATE TABLE MARCA (
	ID_MARCA INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(55) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    INDEX (ID_MARCA)
);

CREATE TABLE PRODUTO (
	ID_PRODUTO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_TIPO_PRODUTO INTEGER NOT NULL,
    ID_MARCA INTEGER NOT NULL,
    NOME VARCHAR(55) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    DESCRICAO VARCHAR(255),
    CONSTRAINT FK_ID_TIPO_PRODUTO FOREIGN KEY (ID_TIPO_PRODUTO) REFERENCES TIPO_PRODUTO(ID_TIPO_PRODUTO),
    CONSTRAINT FK_ID_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA (ID_MARCA),
	INDEX (ID_PRODUTO),
    INDEX (ID_TIPO_PRODUTO),
    INDEX (ID_MARCA)
);

CREATE TABLE LISTA_PRODUTO (
	ID_LISTA INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    MARCADO TINYINT,
    PESO FLOAT,
    QUANTIDADE INTEGER,
    OBS VARCHAR(255),
    PRIMARY KEY(ID_LISTA, ID_PRODUTO),
    CONSTRAINT FK_ID_LISTA FOREIGN KEY (ID_LISTA) REFERENCES LISTA(ID_LISTA),
    CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
    INDEX (ID_LISTA),
    INDEX (ID_PRODUTO)
);

/*Sempre que for colocar uma clausula where procure seguir a seguinte ordem nos filtros por tipo de dado da coluna:

	1 - NUMERICOS
	2 - DATA/HORA
    3 - TEXTO*/