DROP DATABASE IF EXISTS DB_LISTA_MINIMO_LOG;
CREATE DATABASE DB_LISTA_MINIMO_LOG;

-- Log do cliente
CREATE TABLE DB_LISTA_MINIMO_LOG.HISTORICO_CLIENTE_LOG(
	ID_HISTORICO_CLIENTE_LOG INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(55),
    DT_ALTERACAO DATETIME,
    TIPO_ALTERACAO VARCHAR (25),
    TABELA VARCHAR(55)
);

CREATE TABLE DB_LISTA_MINIMO_LOG.CLIENTE_LOG (
	ID_CLIENTE_LOG INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HISTORICO_CLIENTE_LOG INTEGER NOT NULL,
    CAMPO VARCHAR(55),
    VALOR_ANTES VARCHAR(255),
    VALOR_DEPOIS VARCHAR(255),
    CONSTRAINT FK_ID_HISTORICO_CLIENTE_LOG FOREIGN KEY (ID_HISTORICO_CLIENTE_LOG) REFERENCES HISTORICO_CLIENTE_LOG(ID_HISTORICO_CLIENTE_LOG)
);

-- Log da lista
CREATE TABLE DB_LISTA_MINIMO_LOG.HISTORICO_LISTA_LOG(
	ID_HISTORICO_LISTA_LOG INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(55),
    DT_ALTERACAO DATETIME,
    TIPO_ALTERACAO VARCHAR (25),
    TABELA VARCHAR(55)
);

CREATE TABLE DB_LISTA_MINIMO_LOG.LISTA_LOG (
	ID_LISTA_LOG INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HISTORICO_LISTA_LOG INTEGER NOT NULL,
    CAMPO VARCHAR(55),
    VALOR_ANTES VARCHAR(255),
    VALOR_DEPOIS VARCHAR(255),
    CONSTRAINT FK_ID_HISTORICO_LISTA_LOG FOREIGN KEY (ID_HISTORICO_LISTA_LOG) REFERENCES HISTORICO_LISTA_LOG(ID_HISTORICO_LISTA_LOG)
);

-- Log de produto
CREATE TABLE DB_LISTA_MINIMO_LOG.HISTORICO_PRODUTO_LOG(
	ID_HISTORICO_PRODUTO_LOG INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(55),
    DT_ALTERACAO DATETIME,
    TIPO_ALTERACAO VARCHAR (25),
    TABELA VARCHAR(55)
);

CREATE TABLE DB_LISTA_MINIMO_LOG.PRODUTO_LOG (
	ID_PRODUTO_LOG INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HISTORICO_PRODUTO_LOG INTEGER NOT NULL,
    CAMPO VARCHAR(55),
    VALOR_ANTES VARCHAR(255),
    VALOR_DEPOIS VARCHAR(255),
    CONSTRAINT FK_ID_HISTORICO_PRODUTO_LOG FOREIGN KEY (ID_HISTORICO_PRODUTO_LOG) REFERENCES HISTORICO_PRODUTO_LOG(ID_HISTORICO_PRODUTO_LOG)
);

-- Log da Lista Produto
CREATE TABLE DB_LISTA_MINIMO_LOG.HISTORICO_LISTA_PRODUTO_LOG(
	ID_HISTORICO_LISTA_PRODUTO_LOG INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(55),
    DT_ALTERACAO DATETIME,
    TIPO_ALTERACAO VARCHAR (25),
    TABELA VARCHAR(55)
);

CREATE TABLE DB_LISTA_MINIMO_LOG.LISTA_PRODUTO_LOG(
	ID_LISTA_PRODUTO_LOG INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HISTORICO_LISTA_PRODUTO_LOG INTEGER NOT NULL,
    CAMPO VARCHAR(55),
    VALOR_ANTES VARCHAR(255),
    VALOR_DEPOIS VARCHAR(255),
    CONSTRAINT FK_ID_HISTORICO_LISTA_PRODUTO_LOG FOREIGN KEY (ID_HISTORICO_LISTA_PRODUTO_LOG) REFERENCES HISTORICO_LISTA_PRODUTO_LOG(ID_HISTORICO_LISTA_PRODUTO_LOG)
);

DROP USER IF EXISTS 'SISTEMA_MINIMO'@'LOCALHOST';

FLUSH PRIVILEGES;

CREATE USER 'SISTEMA_MINIMO'@'LOCALHOST' IDENTIFIED BY 'XpTO$98245015#';

GRANT SELECT, UPDATE, DELETE ON DB_LISTA_MINIMO.* TO 'SISTEMA_MINIMO'@'LOCALHOST';

-- GRANT SELECT, UPDATE, DELETE ON DB_LISTA_MINIMO_LOG.* TO 'SISTEMA_MINIMO'@'LOCALHOST';

FLUSH PRIVILEGES;

DELIMITER $$
CREATE TRIGGER TRG_CLIENTE_INSERT_LOG_AI AFTER INSERT ON DB_LISTA_MINIMO.CLIENTE FOR EACH ROW
BEGIN
	INSERT INTO DB_LISTA_MINIMO_LOG.HISTORICO_CLIENTE_LOG 
    (USUARIO, DT_ALTERACAO, TIPO_ALTERACAO, TABELA) 
    VALUES (USER(), NOW(), 'INSERT',  'CLIENTE');
    
    SET HISTORICO_CLIENTE_LOG.vULTIMO_ID_HISTORICO_CLIENTE_LOG = LAST_INSERT_ID();
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'ID_CLIENTE', NEW.ID_CLIENTE);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'NOME_CLIENTE', NEW.NOME_CLIENTE);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'CPF', NEW.CPF);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'DATA_NASCIMENTO', NEW.DATA_NASCIMENTO);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'DATA_CADASTRO', NEW.DATA_CADASTRO);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'TIPO_USUARIO', NEW.TIPO_USUARIO);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'NOME_USUARIO', NEW.NOME_USUARIO);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'SENHA', NEW.SENHA);
END $$

CREATE TRIGGER TRG_CLIENTE_AU AFTER UPDATE ON DB_LISTA_MINIMO.CLIENTE FOR EACH ROW
BEGIN
	INSERT INTO DB_LISTA_MINIMO_LOG.HISTORICO_CLIENTE_LOG 
    (USUARIO, DT_ALTERACAO, TIPO_ALTERACAO, TABELA) 
    VALUES (USER(), NOW(), 'UPDATE',  'CLIENTE');
    
    SET vULTIMO_ID_HITORICO_CLIENTE_LOG =  LAST_INSERT_ID();
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'ID_CLIENTE', OLD.ID_CLIENTE, NEW.IDCLIENTE);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'NOME_CLIENTE', OLD.NOME_CLIENTE, NEW.NOME_CLIENTE);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'CPF', OLD.CPF, NEW.CPF);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'DATA_NASCIMENTO', OLD.DATA_NASCIMENTO, NEW.DATA_NASCIMENTO);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'DATA_CADASTRO', OLD.DATA_CADASTRO, NEW.DATA_CADASTRO);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'TIPO_USUARIO', OLD.TIPO_USUARIO, NEW.TIPO_USUARIO);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'NOME_USUARIO', OLD.NOME_USUARIO, NEW.NOME_USUARIO);
    
    INSERT INTO DB_LISTA_MINIMO_LOG.CLIENTE_LOG (ID_HISTORICO, CAMPO, VALOR_ANTES, VALOR_DEPOIS)
    VALUES (vULTIMO_ID_HISTORICO_CLIENTE_LOG, 'SENHA', OLD.SENHA, NEW.SENHA);
END $$
DELIMITER ;